<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="5860" started-at="2015-08-16T17:00:41Z" finished-at="2015-08-16T17:00:47Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="5860" started-at="2015-08-16T17:00:41Z" finished-at="2015-08-16T17:00:47Z">
      <class name="com.faiz.prog.TestGoogle">
        <test-method status="PASS" signature="name()[pri:0, instance:com.faiz.prog.TestGoogle@7437e222]" name="name" is-config="true" duration-ms="5657" started-at="2015-08-16T22:30:41Z" finished-at="2015-08-16T22:30:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- name -->
        <test-method status="FAIL" signature="firstTest()[pri:0, instance:com.faiz.prog.TestGoogle@7437e222]" name="firstTest" duration-ms="114" started-at="2015-08-16T22:30:47Z" finished-at="2015-08-16T22:30:47Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://www.google.co.in/?gfe_rd=cr&ei=vcHQVfqpN8KCvATG0ZPIAg&gws_rd=ssl] but found [http://google.com]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://www.google.co.in/?gfe_rd=cr&ei=vcHQVfqpN8KCvATG0ZPIAg&gws_rd=ssl] but found [http://google.com]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.faiz.prog.TestGoogle.firstTest(TestGoogle.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- firstTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.faiz.prog.TestGoogle@7437e222]" name="tearDown" is-config="true" duration-ms="69" started-at="2015-08-16T22:30:47Z" finished-at="2015-08-16T22:30:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.faiz.prog.TestGoogle -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
